### ISSUE TITLE
Update example doc to support nextJS versions 13/14

### ISSUE THREAD

**Issue by yansavitski** [elastic/search-ui#1017]
Update [doc](https://github.com/elastic/search-ui/blob/main/docs/guides-nextjs-integration.mdx#L51) with integrations search ui and nextJS 13/14 versions.

#### Acceptance criteria:

- [ ]  Example work from the box with 13/14 version of next js
- [ ]  Works with app directory in nextJS
- [ ]  Work with page directory

**Comment by Samiul-TheSoccerFan** [comment]
Adding references as these two issues/threads might get direct benefitted from this change:

https://github.com/elastic/search-ui/issues/1004

https://discuss.elastic.co/t/in-responsive-mode-when-i-select-some-filter-the-filter-automatically-closes-withoutin-responsive-mode-when-i-select-a-filter-the-filter-closes-automatically-without-me-clicking-save-filter-clicking-on-save-filter/353148/9
